name: Build
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc:
          - gcc
          - clang
        options:
          - [--optimization=0]
          - [--optimization=2]
          - [--optimization=2, -Db_lto=true]
          - [--optimization=3]
          - [--optimization=3, -Db_lto=true]
          - [--optimization=s]
        include:
          - cc: gcc
            options: [--optimization=0, -Db_sanitize=address]
            shorthand: O0-asan
          - options: [--optimization=0]
            shorthand: O0
          - options: [--optimization=2]
            shorthand: O2
          - options: [--optimization=2, -Db_lto=true]
            shorthand: O2-lto
          - options: [--optimization=3]
            shorthand: O3
          - options: [--optimization=3, -Db_lto=true]
            shorthand: O3-lto
          - options: [--optimization=s]
            shorthand: Os
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Meson and dependencies
        run: |
          sudo apt-get install \
            meson \
            ninja-build \
            check
      - name: Configure project
        run: |
          CC=${{ matrix.cc }} meson setup \
            --backend=ninja \
            --debug \
            --prefix=/usr \
            ${{ join(matrix.options, ' ') }} \
            build
      - name: Build
        run: ninja -v -C build all
      - name: Test
        run: meson test -C build --verbose --no-rebuild
      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: testlog-${{ github.sha }}-ubuntu-${{ matrix.cc }}-${{ matrix.shorthand }}
          path: build/meson-logs/testlog.txt
      - name: Install
        run: |
          mkdir destdir && DESTDIR=${PWD}/destdir ninja -C build install
      - name: Upload installed tree
        uses: actions/upload-artifact@v4
        with:
          name: libtaco-${{ github.sha }}-ubuntu-${{ matrix.cc }}-${{ matrix.shorthand }}
          path: destdir
  build-mingw:
    name: Build (Windows)
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        options:
          - [--optimization=0]
          - [--optimization=2]
          - [--optimization=2, -Db_lto=true]
          - [--optimization=3]
          - [--optimization=3, -Db_lto=true]
          - [--optimization=s]
        include:
          - options: [--optimization=0]
            shorthand: O0
          - options: [--optimization=2]
            shorthand: O2
          - options: [--optimization=2, -Db_lto=true]
            shorthand: O2-lto
          - options: [--optimization=3]
            shorthand: O3
          - options: [--optimization=3, -Db_lto=true]
            shorthand: O3-lto
          - options: [--optimization=s]
            shorthand: Os
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          msystem: clang64
          pacboy: >-
            toolchain:p
            meson:p
            ninja:p
            check:p
            bison:
            flex:
      - name: Configure project
        run: |
          meson setup \
            --backend=ninja \
            --debug \
            --prefix=/usr \
            ${{ join(matrix.options, ' ') }} \
            build
      - name: Build
        run: ninja -v -C build all
      - name: Test
        run: meson test -C build --verbose --no-rebuild
      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: testlog-${{ github.sha }}-mingw-w64-${{ matrix.shorthand }}
          path: build/meson-logs/testlog.txt
      - name: Install
        run: |
          mkdir destdir && DESTDIR=${PWD}/destdir ninja -C build install
      - name: Upload installed tree
        uses: actions/upload-artifact@v4
        with:
          name: libtaco-${{ github.sha }}-mingw-w64-${{ matrix.shorthand }}
          path: destdir
