name: clang-format
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  format:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install required tools
        run: |
          sudo apt-get install \
            meson \
            ninja-build \
            clang-format \
            check
      - name: Configure project
        run: |
          meson setup \
            --backend=ninja \
            build
      - name: Check code formatting
        run: ninja -v -C build clang-format-check
